on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '**.md'
      - 'playground/**'
      - .editorconfig
      - .gitignore

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - run: npm ci
    - run: node ./index.js
    - run: node ./publish.js
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
