on: [workflow_call, push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - run: deno task generate --no-replace-ids
      - run: deno task test
      - run: deno lint
      - run: deno fmt --check --ext ts

