on:
  workflow_call:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - .github/FUNDING.yml
      - .github/renovate.json
      - '**.md'
      - .idea
      - .editorconfig
      - .gitignore
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - run: deno task generate --no-replace-ids --version=1.0
      - run: deno task test
